### ISSUE TITLE
OpenRadar doesn’t care for non-ASCII characters in the title field

### ISSUE THREAD

**Issue by markmentovai** [timburks/openradar#1]
I had a bug with a smart curly quote in the title field.

When I submitted it, I got an error page that seemed to indicate a problem with Unicode characters. I removed the funny character and resubmitted the report, and OpenRadar accepted it.

Upon returning to “My Radars,” I found that the submission with the funny character in the title was accepted too, I just never got a confirmation, and instead got an error page.

**Comment by timburks** [comment]
I just (finally) updated to the Python 2.7 runtime, which includes better escaping and unicode string handling. It worked for me when I tested by posting “ in a few Radar fields.
