### ISSUE TITLE
Revert robots.txt allowing Open Radar to appear in web searches

### ISSUE THREAD

**Issue by pyrtsa** [timburks/openradar#19]
The current [`robots.txt`](https://github.com/timburks/openradar/blob/master/python/static/robots.txt) file blocks all robots from accessing the site, effectively making Open Radar _ungoogleable_:

``` txt
User-agent: *
Disallow: /
```

I can see the change was made for [maintenance cost reasons](https://github.com/timburks/openradar/commit/5b119fa64630d941ebff3c5962085bb3b72ba370), but given its central position in the fruit community, why not consider "search-engine-optimising" Open Radar at least as much as allowing the use of external search engines?

**Comment by timburks** [comment]
In progress. Thanks.
