### ISSUE TITLE
Blocks of code?

### ISSUE THREAD

**Issue by Qix-** [timburks/openradar#29]
Is there a way to have formatted blocks of code? I pasted some since file attachments aren't allowed and of course all of the `*` for pointers are turning the block into an italicized mess.

**Comment by timburks** [comment]
Hi Josh,

Was this in a radar body or a comment? Radar descriptions are plain text
(<pre> elements) and comments are in Markdown. Here's a link to a radar
with code in a Markdown-formatted comment: http://www.openradar.me/23224354

Tim

**Comment by Qix-** [comment]
Aha, cool thanks :)
