### ISSUE TITLE
For Apple IPs, change the radar link to radar://

### ISSUE THREAD

**Issue by drfindley** [timburks/openradar#35]
If the browser has a 17.X.X.X address, change the http://www.openradar.me/27988819 to radar://27988819 so internal Apple employees can open it easily. This might be the ever so slightest help in getting an radar some traction.

**Comment by AkdM** [comment]
On each header bug report, the `Number` row has two links actually: the `rdar` and `http` one. Simply click on the first one.

![screenshot](https://i.imgur.com/2RcG3Zs.png)

**Comment by drfindley** [comment]
Ah, either that feature is new or more likely, I completely missed it.

With an easy link like that, this works for me.
